### ISSUE TITLE
No release since days

### ISSUE THREAD

**Issue by holyhope** [mhausenblas/kcf#10]
Hello,

My [last PR](https://github.com/kubectl-plus/kcf/pull/9) was merged, but there is no release since then.
Is it possible to have a new release on krew please?

Thanks a lot.

**Comment by mhausenblas** [comment]
Thanks for the reminder, indeed! @rajatjindal do you have some cycles to cut a release and potentially also update the `krew`  index (I believe that's still necessary, or?)

**Comment by rajatjindal** [comment]
Yes i can cut the release today.

**Comment by rajatjindal** [comment]
the krew-index update is automatic. It didnt get merged automatically though as there was a drift between our template file and file in krew-index. 

It was due to a mass update PR done in krew-index to remove duplication of some documentation. I've submitted the PR #12  to fix that, and next release onwards it should get merge automatically.

**Comment by mhausenblas** [comment]
Fantastic, thank you @rajatjindal! I suppose we can close this issue then?

**Comment by holyhope** [comment]
Not sure why, but the release is not yet available on krew:
```
Upgrading plugin: fleet                                                                                                                                       
Skipping plugin fleet, it is already on the newest version
```
```
NAME: fleet
URI: https://github.com/kubectl-plus/kcf/releases/download/v0.1.7/fleet_darwin_amd64.tar.gz
SHA256: f78eda6260001e3f0963ab3694a0354c64b45946f5d09c4db5a7ff799be6ec85
VERSION: v0.1.7
HOMEPAGE: https://github.com/kubectl-plus/kcf
DESCRIPTION: 
Allows to get an overview and details on a fleet of Kubernetes clusters.
The top-level command lists all active clusters found in the kubeconfig provided.
For each cluster, configuration info such as the control plane version or 
API server endpoint are displayed, as well as select stats, for example, 
the number of worker nodes or namespaces found in the cluster.

CAVEATS:
\
 | Usage:
 |   $ kubectl fleet
 | 
 | For additional options:
 |   $ kubectl fleet --help
 |   or https://github.com/kubectl-plus/kcf/blob/v0.1.4/doc/USAGE.md
/
```

**Comment by rajatjindal** [comment]
sorry, I should have been more clear. 

There was a drift between our version of spec and krew-index version of spec, due to which the new version was NOT automatically accepted.

I've cut a new version v0.1.9 which fixes that prob. It should be available in krew-index now.
