### ISSUE TITLE
unknown flag: --kubeconfig when issued details subcommand

### ISSUE THREAD

**Issue by developer-guy** [mhausenblas/kcf#11]
`$ k fleet details <context> --kubeconfig some-kubeconf 
`

I think --kubeconfig flag not added to details subcommand.

**Comment by mhausenblas** [comment]
Yep, I can reproduce this, seems the global `kubectl` flags such as `--kubeconfig` are only available to the top-level command but not subcommands. Not sure how to address this, tho … @rajatjindal have you seen this before?

**Comment by rajatjindal** [comment]
I can check this later tonight.

**Comment by rajatjindal** [comment]
Hi @developer-guy ,

could you please try the fix from https://github.com/kubectl-plus/kcf/pull/14 and confirm if that resolves the issue for you.

many thanks

**Comment by developer-guy** [comment]
> Hi @developer-guy ,
> 
> 
> 
> could you please try the fix from https://github.com/kubectl-plus/kcf/pull/14 and confirm if that resolves the issue for you.
> 
> 
> 
> many thanks

Ok , i will try as soon as possible , you’re welcome 🙏

**Comment by rajatjindal** [comment]
fixed by #14
