### ISSUE TITLE
add provider information to the fleet

### ISSUE THREAD

**Issue by rajatjindal** [mhausenblas/kcf#3]
from #krew channel, it will be nice to add provider to the fleet output. (e.g. kind, gke, eks etc)

**Comment by rajatjindal** [comment]
I am trying to add this feature today.

**Comment by mhausenblas** [comment]
Cool! Also, let me know if you'd like me to create a new GitHub org, maybe `fleet` or the like and move this repo there, might make things easier, going forward.

**Comment by rajatjindal** [comment]
sure, that will be great.

**Comment by rajatjindal** [comment]
The PR is merged to add this feature.
